import { useRef, useState } from "react";
import { motion } from "framer-motion";
import { Play, Volume2, VolumeX, Heart, MessageCircle, Send, Bookmark } from "lucide-react";

const vp = { once: true, amount: 0.05 };

const videos = [
  {
    src: "/ai-video-sample.mp4",
    caption: "AI will automate work. Or will it? 🤖",
    likes: "2.4k",
    comments: "48",
    hashtags: ["#AIVideo", "#Higgsfield", "#AIMarketing"],
  },
  {
    src: "/ai-video-2.mp4",
    caption: "Cinematic worlds, generated by AI 🏔️",
    likes: "1.8k",
    comments: "32",
    hashtags: ["#AIVideo", "#CinematicAI", "#GenerativeVideo"],
  },
];

const ReelPhone = ({ video, delay }) => {
  const videoRef = useRef(null);
  const [playing, setPlaying] = useState(false);
  const [muted, setMuted] = useState(true);

  const togglePlay = () => {
    if (!videoRef.current) return;
    if (playing) {
      videoRef.current.pause();
    } else {
      videoRef.current.play();
    }
    setPlaying(!playing);
  };

  const toggleMute = (e) => {
    e.stopPropagation();
    if (!videoRef.current) return;
    videoRef.current.muted = !muted;
    setMuted(!muted);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 32 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={vp}
      transition={{ duration: 0.65, delay }}
      className="flex-shrink-0 flex justify-center"
    >
      {/* Phone shell */}
      <div className="relative w-[250px] sm:w-[270px]">
        {/* Phone border */}
        <div className="relative rounded-[40px] bg-gray-900 p-[10px] shadow-[0_40px_80px_rgba(0,0,0,0.25)]">
          {/* Dynamic island */}
          <div className="absolute top-[18px] left-1/2 -translate-x-1/2 w-[90px] h-[28px] bg-black rounded-full z-20" />

          {/* Screen */}
          <div
            className="relative rounded-[32px] overflow-hidden bg-black cursor-pointer"
            style={{ aspectRatio: "9/16" }}
            onClick={togglePlay}
          >
            <video
              ref={videoRef}
              src={video.src}
              className="absolute inset-0 w-full h-full object-cover"
              muted
              playsInline
              loop
              onPlay={() => setPlaying(true)}
              onPause={() => setPlaying(false)}
            />

            {/* Instagram Reel UI overlay */}
            <div className="absolute inset-0 flex flex-col justify-between pointer-events-none">

              {/* Top bar */}
              <div className="pt-10 px-3 flex items-center justify-between">
                <div className="flex items-center gap-1.5">
                  <div className="w-5 h-5 rounded-full bg-gradient-to-br from-pink-500 via-red-500 to-yellow-400 p-[1.5px]">
                    <div className="w-full h-full rounded-full bg-black flex items-center justify-center">
                      <span className="text-white font-bold" style={{fontSize:"7px"}}>R</span>
                    </div>
                  </div>
                  <span className="font-inter text-white text-[9px] font-semibold drop-shadow">roshan</span>
                  <span className="border border-white/70 rounded text-white px-1" style={{fontSize:"7px"}}>Follow</span>
                </div>
                <button
                  onClick={toggleMute}
                  className="pointer-events-auto w-6 h-6 rounded-full bg-black/40 flex items-center justify-center"
                >
                  {muted
                    ? <VolumeX size={10} className="text-white" />
                    : <Volume2 size={10} className="text-white" />
                  }
                </button>
              </div>

              {/* Play overlay */}
              <div className={`absolute inset-0 flex items-center justify-center transition-opacity duration-200 pointer-events-none ${playing ? "opacity-0" : "opacity-100"}`}>
                <div className="w-14 h-14 rounded-full bg-black/35 backdrop-blur-sm flex items-center justify-center">
                  <Play size={20} className="text-white ml-0.5" />
                </div>
              </div>

              {/* Right side actions */}
              <div className="absolute right-2.5 bottom-20 flex flex-col items-center gap-4">
                {[
                  { id: "like", icon: Heart, label: video.likes },
                  { id: "comment", icon: MessageCircle, label: video.comments },
                  { id: "send", icon: Send, label: "" },
                  { id: "save", icon: Bookmark, label: "" },
                ].map(({ id, icon: Icon, label }) => (
                  <div key={id} className="flex flex-col items-center gap-0.5">
                    <div className="w-7 h-7 rounded-full bg-black/30 backdrop-blur-sm flex items-center justify-center">
                      <Icon size={13} className="text-white" fill={Icon === Heart ? "white" : "none"} />
                    </div>
                    {label && <span className="font-inter text-white text-[8px] font-semibold drop-shadow">{label}</span>}
                  </div>
                ))}
              </div>

              {/* Bottom caption */}
              <div className="px-3 pb-5 bg-gradient-to-t from-black/60 via-black/20 to-transparent pt-8">
                <p className="font-inter text-white text-[9.5px] font-semibold leading-relaxed drop-shadow mb-1">
                  {video.caption}
                </p>
                <p className="font-inter text-white/75 text-[8.5px] leading-relaxed drop-shadow">
                  Created with <span className="text-white font-semibold">Higgsfield AI</span>
                </p>
                <div className="flex gap-1 flex-wrap mt-1.5">
                  {video.hashtags.map(t => (
                    <span key={t} className="font-inter text-[7.5px] text-blue-300 font-medium">{t}</span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Home indicator */}
        <div className="flex justify-center mt-2">
          <div className="w-24 h-1 bg-white/20 rounded-full" />
        </div>
      </div>
    </motion.div>
  );
};

export default function AIVideo() {
  return (
    <section id="ai-video" className="py-20 bg-gradient-to-b from-transparent via-blue-50/20 to-transparent">
      <div className="max-w-6xl mx-auto px-6">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={vp}
          transition={{ duration: 0.55 }}
          className="text-center mb-14"
        >
          <div className="section-label mb-3">Creative Work</div>
          <h2 className="font-grotesk text-[26px] sm:text-[34px] lg:text-[40px] font-bold tracking-tight text-ink leading-[1.1]">
            AI <span className="text-gradient">Video Creation</span>
          </h2>
          <p className="font-inter text-gray-400 text-[15px] mt-3 max-w-[460px] mx-auto">
            Cinematic AI-generated videos made with Higgsfield — exploring storytelling through generative video tools.
          </p>
        </motion.div>

        <div className="flex flex-col lg:flex-row items-center lg:items-start justify-center gap-12 lg:gap-10">

          {/* Phone mockups */}
          <div className="flex flex-col sm:flex-row gap-10 sm:gap-8 justify-center">
            {videos.map((video, i) => (
              <ReelPhone key={video.src} video={video} delay={0.1 + i * 0.15} />
            ))}
          </div>

          {/* Right — description */}
          <motion.div
            initial={{ opacity: 0, x: 32 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={vp}
            transition={{ duration: 0.65, delay: 0.2 }}
            className="flex-1 text-center lg:text-left max-w-[400px] lg:pt-8"
          >
            <div className="inline-flex items-center gap-2 bg-blue-50 border border-blue-200 rounded-full px-3 py-1 mb-5">
              <span className="text-[11px]">🎬</span>
              <span className="font-inter text-[11px] font-semibold text-blue-700 uppercase tracking-wide">AI Generated</span>
            </div>

            <h3 className="font-grotesk font-bold text-ink text-[22px] sm:text-[26px] leading-tight tracking-tight mb-3">
              Stories without
              <br />
              <span className="text-gradient">a camera or crew.</span>
            </h3>

            <p className="font-inter text-gray-500 text-[14.5px] leading-relaxed mb-6">
              Cinematic shorts exploring the future of AI, work, and generated worlds — created entirely with Higgsfield AI's video generation platform.
            </p>

            <div className="mb-6">
              <div className="font-inter text-[11px] font-semibold text-gray-400 uppercase tracking-wider mb-3">Tools Used</div>
              <div className="flex flex-wrap gap-2 justify-center lg:justify-start">
                {["Higgsfield AI", "AI Video Generation", "Cinematic Prompting", "Marketing Content"].map((tag) => (
                  <span key={tag} className="px-3 py-1.5 bg-white border border-border rounded-full font-inter text-[12px] font-medium text-gray-600 shadow-soft">
                    {tag}
                  </span>
                ))}
              </div>
            </div>

            <div className="bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-100 rounded-2xl p-4">
              <div className="font-grotesk font-semibold text-blue-800 text-[13px] mb-1">Why AI video?</div>
              <p className="font-inter text-blue-700 text-[12.5px] leading-relaxed">
                AI video tools allow marketers to produce cinematic content without a production budget — making high-quality storytelling accessible at scale.
              </p>
            </div>
          </motion.div>

        </div>
      </div>
    </section>
  );
}
